services:
    gateway:
        ports:
        # Binding only to localhost (127.0.0.1) loopback network interface
        # and not to all network interfaces of the host for security
        # reasons - so as to not expose the service to outside devices
        # that can access the host through other network interfaces
        - "127.0.0.1:8080:8080"
        image: payment-gateway
        build:
            context: .
            args:
                SERVICE_NAME: payment-gateway
        # # TODO: Add `develop` field - for example to help with
        # # rebuilding service image when service source code changes
        # # https://docs.docker.com/reference/compose-file/develop/
        # develop:
        #     watch:
        #         - path: ./cmd/payment-gateway
        #           action: rebuild

    processor:
        image: payment-processor
        build:
            context: .
            args:
                SERVICE_NAME: payment-processor
        # # TODO: Add `develop` field - for example to help with
        # # rebuilding service image when service source code changes
        # # https://docs.docker.com/reference/compose-file/develop/
        # develop:
        #     watch:
        #         - path: ./cmd/payment-processor
        #           action: rebuild
